const apiKeys = {
  HORSE_CARE_INFORMATION: import.meta.env
    .VITE_APP_API_KEYS_HORSE_CARE_INFORMATION,
  TRAINER_DETAILS: import.meta.env.VITE_APP_API_KEYS_TRAINER_DETAILS,
  HORSEMAN_DETAILS: import.meta.env.VITE_APP_API_KEYS_HORSEMAN_DETAILS,
  RACEHORSE_PERFORMANCE_INFORMATION: import.meta.env
    .VITE_APP_API_KEYS_RACEHORSE_PERFORMANCE_INFORMATION,
  RACE_RECORD_INFORMATION: import.meta.env
    .VITE_APP_API_KEYS_RACE_RECORD_INFORMATION,
  RACEHORSE_DETAILS: import.meta.env.VITE_APP_API_KEYS_RACEHORSE_DETAILS,
};

export default apiKeys;
